using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OptimizationDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            HttpCookie cookie = new HttpCookie("BigCookie", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut lobortis quam. Vivamus sit amet laoreet tortor. Phasellus quis pulvinar nibh, id ullamcorper justo. Nulla vehicula dolor ut tempus iaculis. Quisque non urna fringilla, molestie odio id, convallis felis. Sed sed neque vehicula, elementum libero sed, adipiscing orci. Phasellus porta nulla tellus, a semper lectus tempor eu. Aenean sagittis pretium lobortis. Curabitur egestas neque sit amet bibendum cursus. Suspendisse quis libero luctus, accumsan nunc quis, interdum ante. Phasellus vitae blandit elit. Quisque egestas lacus eu tortor pulvinar consequat. In hac habitasse platea dictumst. Curabitur molestie dui faucibus orci vulputate, in malesuada nibh mollis.

Nullam erat nibh, commodo id mi fermentum, pharetra porta sem. Maecenas eu sem sed mauris tristique egestas vel eu turpis. Proin ut consequat massa. Suspendisse arcu urna, blandit non placerat eget, auctor vel mi. Ut augue elit, auctor vitae congue sit amet, sagittis vehicula eros. Vestibulum semper nisl a justo posuere ullamcorper. Nam tincidunt neque lorem, eget iaculis velit viverra ac. Donec eu lectus dui. Suspendisse et tortor non purus elementum suscipit. Vestibulum in tellus vitae velit feugiat feugiat et non tellus. Nulla lorem tortor, feugiat non odio id, fringilla imperdiet diam. Etiam ultrices eros condimentum turpis iaculis scelerisque.

Fusce aliquet dolor vitae molestie laoreet. Nunc interdum tortor lobortis ligula porta iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras varius, nisl ac porttitor hendrerit, tellus nisi pharetra sapien, quis placerat quam mi sed dolor. Morbi dolor tellus, tincidunt in varius varius, semper a leo. Donec mattis sem magna, ac euismod enim faucibus a. Integer ultrices, quam ac vestibulum dapibus, elit enim condimentum quam, non faucibus turpis neque commodo lorem. Vestibulum egestas arcu turpis, at imperdiet ipsum elementum a. Ut risus lorem, vulputate eget cursus nec, venenatis eu lorem. Nunc massa nibh, sagittis ac diam sit amet, euismod congue velit. Nam pharetra metus vitae feugiat rhoncus. Mauris viverra tortor elit, sed vestibulum mauris laoreet id. Ut ultrices in lectus non tristique. Sed vitae malesuada elit, quis vestibulum ante. Sed feugiat nunc at metus tincidunt, vitae molestie mauris posuere. Quisque nisi quam, tempor sit amet sapien eu, semper interdum leo.

Maecenas a urna sed quam sagittis aliquam. Nunc condimentum malesuada risus eu blandit. Suspendisse mollis nec risus non imperdiet. Curabitur volutpat, felis non elementum accumsan, purus erat hendrerit sapien, rhoncus adipiscing nisi tellus vel nibh. Duis ac purus mauris. Nullam id iaculis dolor. Fusce a aliquet magna. Cras feugiat, eros at accumsan feugiat, neque purus elementum lectus, et porta nisi massa luctus lacus. Curabitur sed semper diam, ut facilisis metus. Quisque rhoncus malesuada sem, ac sodales sapien. Nullam sit amet sem orci. Pellentesque venenatis enim libero, a posuere massa convallis ut. Duis ornare tortor in vehicula rutrum. Sed sed neque ultrices libero aliquam pretium.

Duis sed molestie est. Cras at convallis leo. Proin eget dictum diam. Aenean adipiscing facilisis turpis sit amet interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean vel nisi commodo, mattis lorem non, vulputate est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec feugiat rutrum eros ac semper. Quisque iaculis porttitor erat, sit amet sagittis nisi consequat nec. In et euismod ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut lobortis quam. Vivamus sit amet laoreet tortor. Phasellus quis pulvinar nibh, id ullamcorper justo. Nulla vehicula dolor ut tempus iaculis. Quisque non urna fringilla, molestie odio id, convallis felis. Sed sed neque vehicula, elementum libero sed, adipiscing orci. Phasellus porta nulla tellus, a semper lectus tempor eu. Aenean sagittis pretium lobortis. Curabitur egestas neque sit amet bibendum cursus. Suspendisse quis libero luctus, accumsan nunc quis, interdum ante. Phasellus vitae blandit elit. Quisque egestas lacus eu tortor pulvinar consequat. In hac habitasse platea dictumst. Curabitur molestie dui faucibus orci vulputate, in malesuada nibh mollis.

Nullam erat nibh, commodo id mi fermentum, pharetra porta sem. Maecenas eu sem sed mauris tristique egestas vel eu turpis. Proin ut consequat massa. Suspendisse arcu urna, blandit non placerat eget, auctor vel mi. Ut augue elit, auctor vitae congue sit amet, sagittis vehicula eros. Vestibulum semper nisl a justo posuere ullamcorper. Nam tincidunt neque lorem, eget iaculis velit viverra ac. Donec eu lectus dui. Suspendisse et tortor non purus elementum suscipit. Vestibulum in tellus vitae velit feugiat feugiat et non tellus. Nulla lorem tortor, feugiat non odio id, fringilla imperdiet diam. Etiam ultrices eros condimentum turpis iaculis scelerisque.

Fusce aliquet dolor vitae molestie laoreet. Nunc interdum tortor lobortis ligula porta iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras varius, nisl ac porttitor hendrerit, tellus nisi pharetra sapien, quis placerat quam mi sed dolor. Morbi dolor tellus, tincidunt in varius varius, semper a leo. Donec mattis sem magna, ac euismod enim faucibus a. Integer ultrices, quam ac vestibulum dapibus, elit enim condimentum quam, non faucibus turpis neque commodo lorem. Vestibulum egestas arcu turpis, at imperdiet ipsum elementum a. Ut risus lorem, vulputate eget cursus nec, venenatis eu lorem. Nunc massa nibh, sagittis ac diam sit amet, euismod congue velit. Nam pharetra metus vitae feugiat rhoncus. Mauris viverra tortor elit, sed vestibulum mauris laoreet id. Ut ultrices in lectus non tristique. Sed vitae malesuada elit, quis vestibulum ante. Sed feugiat nunc at metus tincidunt, vitae molestie mauris posuere. Quisque nisi quam, tempor sit amet sapien eu, semper interdum leo.

Maecenas a urna sed quam sagittis aliquam. Nunc condimentum malesuada risus eu blandit. Suspendisse mollis nec risus non imperdiet. Curabitur volutpat, felis non elementum accumsan, purus erat hendrerit sapien, rhoncus adipiscing nisi tellus vel nibh. Duis ac purus mauris. Nullam id iaculis dolor. Fusce a aliquet magna. Cras feugiat, eros at accumsan feugiat, neque purus elementum lectus, et porta nisi massa luctus lacus. Curabitur sed semper diam, ut facilisis metus. Quisque rhoncus malesuada sem, ac sodales sapien. Nullam sit amet sem orci. Pellentesque venenatis enim libero, a posuere massa convallis ut. Duis ornare tortor in vehicula rutrum. Sed sed neque ultrices libero aliquam pretium.

Duis sed molestie est. Cras at convallis leo. Proin eget dictum diam. Aenean adipiscing facilisis turpis sit amet interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean vel nisi commodo, mattis lorem non, vulputate est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec feugiat rutrum eros ac semper. Quisque iaculis porttitor erat, sit amet sagittis nisi consequat nec. In et euismod ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut lobortis quam. Vivamus sit amet laoreet tortor. Phasellus quis pulvinar nibh, id ullamcorper justo. Nulla vehicula dolor ut tempus iaculis. Quisque non urna fringilla, molestie odio id, convallis felis. Sed sed neque vehicula, elementum libero sed, adipiscing orci. Phasellus porta nulla tellus, a semper lectus tempor eu. Aenean sagittis pretium lobortis. Curabitur egestas neque sit amet bibendum cursus. Suspendisse quis libero luctus, accumsan nunc quis, interdum ante. Phasellus vitae blandit elit. Quisque egestas lacus eu tortor pulvinar consequat. In hac habitasse platea dictumst. Curabitur molestie dui faucibus orci vulputate, in malesuada nibh mollis.

Nullam erat nibh, commodo id mi fermentum, pharetra porta sem. Maecenas eu sem sed mauris tristique egestas vel eu turpis. Proin ut consequat massa. Suspendisse arcu urna, blandit non placerat eget, auctor vel mi. Ut augue elit, auctor vitae congue sit amet, sagittis vehicula eros. Vestibulum semper nisl a justo posuere ullamcorper. Nam tincidunt neque lorem, eget iaculis velit viverra ac. Donec eu lectus dui. Suspendisse et tortor non purus elementum suscipit. Vestibulum in tellus vitae velit feugiat feugiat et non tellus. Nulla lorem tortor, feugiat non odio id, fringilla imperdiet diam. Etiam ultrices eros condimentum turpis iaculis scelerisque.

Fusce aliquet dolor vitae molestie laoreet. Nunc interdum tortor lobortis ligula porta iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras varius, nisl ac porttitor hendrerit, tellus nisi pharetra sapien, quis placerat quam mi sed dolor. Morbi dolor tellus, tincidunt in varius varius, semper a leo. Donec mattis sem magna, ac euismod enim faucibus a. Integer ultrices, quam ac vestibulum dapibus, elit enim condimentum quam, non faucibus turpis neque commodo lorem. Vestibulum egestas arcu turpis, at imperdiet ipsum elementum a. Ut risus lorem, vulputate eget cursus nec, venenatis eu lorem. Nunc massa nibh, sagittis ac diam sit amet, euismod congue velit. Nam pharetra metus vitae feugiat rhoncus. Mauris viverra tortor elit, sed vestibulum mauris laoreet id. Ut ultrices in lectus non tristique. Sed vitae malesuada elit, quis vestibulum ante. Sed feugiat nunc at metus tincidunt, vitae molestie mauris posuere. Quisque nisi quam, tempor sit amet sapien eu, semper interdum leo.

Maecenas a urna sed quam sagittis aliquam. Nunc condimentum malesuada risus eu blandit. Suspendisse mollis nec risus non imperdiet. Curabitur volutpat, felis non elementum accumsan, purus erat hendrerit sapien, rhoncus adipiscing nisi tellus vel nibh. Duis ac purus mauris. Nullam id iaculis dolor. Fusce a aliquet magna. Cras feugiat, eros at accumsan feugiat, neque purus elementum lectus, et porta nisi massa luctus lacus. Curabitur sed semper diam, ut facilisis metus. Quisque rhoncus malesuada sem, ac sodales sapien. Nullam sit amet sem orci. Pellentesque venenatis enim libero, a posuere massa convallis ut. Duis ornare tortor in vehicula rutrum. Sed sed neque ultrices libero aliquam pretium.

Duis sed molestie est. Cras at convallis leo. Proin eget dictum diam. Aenean adipiscing facilisis turpis sit amet interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean vel nisi commodo, mattis lorem non, vulputate est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec feugiat rutrum eros ac semper. Quisque iaculis porttitor erat, sit amet sagittis nisi consequat nec. In et euismod ante.");
            HttpContext.Response.Cookies.Add(cookie);
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}